owner: greatnessinabox # Your GitHub organization or username, where this repository lives
repo: site-monitors # The name of this repository

sites:
  - name: TED
    url: https://www.ted.com
  - name: Robert Morris
    url: https://pastorrobert.com
  - name: Such Great Heights
    url: https://suchgreatheights.com
  - name: India Earl Education
    url: https://indiaearleducation.com
  - name: Malibu Juice Club
    url: https://malibujuiceclub.com
  - name: Marquis Codes
    url: https://marquis.codes
  - name: Kebrado
    url: https://kebrado.com
  - name: Unanimous Media
    url: https://unanimousmedia.com

status-website:
  baseUrl: /site-monitors
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Site Monitors
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
